### ISSUE TITLE
Improve the serialization by ignoring string2 if string1 == null

### ISSUE THREAD

**Issue by rocboronat** [backpack-serializers/backpacker-kotlin#4]
Hey @EsteveAguilera !

Just washing my teeth while I had an idea. Right now, as the backpack has lots of parameters, the serialization is not incredibly faster. For example, we are checking if all strings are null, but we can avoid checking string2 if string1 is null. But we have to explain it at the readme, because is a decision to speed up performance that everyone should know.

Share your thoughts, please! I can vote 👍because it will improve performance, but I can also vote 👎because it's premature optimization and we don't know how much time it will save.

**Comment by EsteveAguilera** [comment]
So, here we are, talking about "premature optimization" with 17 commits... 😅 

Right now the performance shows a huge difference... it can be better? maybe, but do we really need those 'we do not how much' fewer milliseconds now? I guess that talking in percentage it will not be so significant.

**Comment by rocboronat** [comment]
Noice! I'll think about again it while brushing my teeth 😂

**Comment by rocboronat** [comment]
I did some numbers! Just tried backpacking the QuitNow! chat using Backpacker and Gson, and Gson wins on serializing, and loses on deserializing. Open source community, sorry for not sharing the source. I written it so fast in a private project.

These are the results:

Backpacker serializing took 17.669ms
Backpacker deserializing took 12.734ms
Gson serializing took 13.885ms
Gson deserializing took 48.199ms

I guess that if we improve the code just by checking if string1 is not null before checking string2, it will be a huge performance improvement on serialization.

**Comment by rocboronat** [comment]
We can't do this. If we do it, we don't allow apps to have nulls. And that could kill the whole library. @EsteveAguilera if you agree, close this issue and forget my proactivity :·D

**Comment by EsteveAguilera** [comment]
Oh, good point! I didn't even think about it! 
The intention was good 😉 , closing issue...

**Comment by rocboronat** [comment]
@EsteveAguilera only for the information. I made a tailored proto for the QuitNow! chat, just to compare with Backpacker, and here are the results:

Gson serializing took 17.147ms
Gson deserializing took 51.378ms
Gson message needs 18.138 bytes

Backpacker serializing took 18.806ms
Backpacker deserializing took 14.470ms
Backpacker message needs 11.114 bytes

Protobuffers serializing took 3.475ms
Protobuffers deserializing took 2.917ms
Protobuffers message needs 10.994 bytes
